package fr_upem_scheduler;


/**
* fr_upem_scheduler/RequestHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from scheduler.idl
* mardi 13 mars 2018 14 h 11 CET
*/

abstract public class RequestHelper
{
  private static String  _id = "IDL:fr_upem_scheduler/Request:1.0";

  public static void insert (org.omg.CORBA.Any a, fr_upem_scheduler.Request that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static fr_upem_scheduler.Request extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [4];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[0] = new org.omg.CORBA.StructMember (
            "request_object",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[1] = new org.omg.CORBA.StructMember (
            "request_interface",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[2] = new org.omg.CORBA.StructMember (
            "request_operation",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_any);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_sequence_tc (0, _tcOf_members0);
          _members0[3] = new org.omg.CORBA.StructMember (
            "ParameterList",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (fr_upem_scheduler.RequestHelper.id (), "Request", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static fr_upem_scheduler.Request read (org.omg.CORBA.portable.InputStream istream)
  {
    fr_upem_scheduler.Request value = new fr_upem_scheduler.Request ();
    value.request_object = istream.read_string ();
    value.request_interface = istream.read_string ();
    value.request_operation = istream.read_string ();
    int _len0 = istream.read_long ();
    value.ParameterList = new org.omg.CORBA.Any[_len0];
    for (int _o1 = 0;_o1 < value.ParameterList.length; ++_o1)
      value.ParameterList[_o1] = istream.read_any ();
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, fr_upem_scheduler.Request value)
  {
    ostream.write_string (value.request_object);
    ostream.write_string (value.request_interface);
    ostream.write_string (value.request_operation);
    ostream.write_long (value.ParameterList.length);
    for (int _i0 = 0;_i0 < value.ParameterList.length; ++_i0)
      ostream.write_any (value.ParameterList[_i0]);
  }

}
