package fr_upem_scheduler;


/**
* fr_upem_scheduler/Request.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from scheduler.idl
* mardi 13 mars 2018 14 h 11 CET
*/

public final class Request implements org.omg.CORBA.portable.IDLEntity
{
  public String request_object = null;
  public String request_interface = null;
  public String request_operation = null;
  public org.omg.CORBA.Any ParameterList[] = null;

  public Request ()
  {
  } // ctor

  public Request (String _request_object, String _request_interface, String _request_operation, org.omg.CORBA.Any[] _ParameterList)
  {
    request_object = _request_object;
    request_interface = _request_interface;
    request_operation = _request_operation;
    ParameterList = _ParameterList;
  } // ctor

} // class Request
