package fr_upem_scheduler;


/**
* fr_upem_scheduler/Scheduler.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from scheduler.idl
* mardi 13 mars 2018 14 h 11 CET
*/

public interface Scheduler extends SchedulerOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Scheduler
