package fr_upem_scheduler;

/**
* fr_upem_scheduler/SchedulerHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from scheduler.idl
* mardi 13 mars 2018 14 h 11 CET
*/

public final class SchedulerHolder implements org.omg.CORBA.portable.Streamable
{
  public fr_upem_scheduler.Scheduler value = null;

  public SchedulerHolder ()
  {
  }

  public SchedulerHolder (fr_upem_scheduler.Scheduler initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = fr_upem_scheduler.SchedulerHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    fr_upem_scheduler.SchedulerHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return fr_upem_scheduler.SchedulerHelper.type ();
  }

}
