package fr_upem_scheduler;


/**
* fr_upem_scheduler/SchedulerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from scheduler.idl
* mardi 13 mars 2018 14 h 11 CET
*/

public interface SchedulerOperations 
{
  boolean postRequest (fr_upem_scheduler.Request r);
  fr_upem_scheduler.Request getRequest (short index);
  boolean checkValues (fr_upem_scheduler.Request r) throws fr_upem_scheduler.unknown_values;
  void removeRequest (short index);
} // interface SchedulerOperations
