package fr_upem_scheduler;

/**
* fr_upem_scheduler/unknown_valuesHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from scheduler.idl
* mardi 13 mars 2018 14 h 11 CET
*/

public final class unknown_valuesHolder implements org.omg.CORBA.portable.Streamable
{
  public fr_upem_scheduler.unknown_values value = null;

  public unknown_valuesHolder ()
  {
  }

  public unknown_valuesHolder (fr_upem_scheduler.unknown_values initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = fr_upem_scheduler.unknown_valuesHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    fr_upem_scheduler.unknown_valuesHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return fr_upem_scheduler.unknown_valuesHelper.type ();
  }

}
