package fr_upem_scheduler;


/**
* fr_upem_scheduler/unknown_values.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from scheduler.idl
* mardi 13 mars 2018 14 h 11 CET
*/

public final class unknown_values extends org.omg.CORBA.UserException
{
  public String message = null;

  public unknown_values ()
  {
    super(unknown_valuesHelper.id());
  } // ctor

  public unknown_values (String _message)
  {
    super(unknown_valuesHelper.id());
    message = _message;
  } // ctor


  public unknown_values (String $reason, String _message)
  {
    super(unknown_valuesHelper.id() + "  " + $reason);
    message = _message;
  } // ctor

} // class unknown_values
